title: Nate Cook
theme: jekyll-theme-cayman
description: University of Illinois Chicago | PhD student | Bilingualism, Emotion, Psychophysiology (EDA, EEG), Computational Linguistics/NLP
show_downloads: false
